import "@/styles/globals.css";
import "@/styles/gray-color.css";

import { type Metadata } from "next";
import { TRPCReactProvider } from "@/trpc/react";
import { useDict } from "@/hooks/use-dict";
import { Quicksand } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import { Providers } from "@/components/providers/providers";

export const dynamic = "force-dynamic";

export const metadata: Metadata = {
  title: "Lontra Agíl",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/lontra-icon.svg" }],
};

const quicksand = Quicksand({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-quicksand",
});

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const { lang } = await useDict();

  return (
    <html lang={lang} data-theme="landing-page'">
      <body className={`${quicksand.variable} font-sans antialiased`}>
        <ClerkProvider>
          <Providers>
            <TRPCReactProvider>{children}</TRPCReactProvider>
          </Providers>
        </ClerkProvider>
      </body>
    </html>
  );
}
